/*
 * Copyright 2013 Small Batch, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
;(function(window,document,undefined){
var h=!0,l=null,m=!1;this.ra=h;function aa(a,b,c){return a.call.apply(a.bind,arguments)}function ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}
function n(a,b,c){n=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;return n.apply(l,arguments)}var r=Date.now||function(){return+new Date};function ca(a,b){this.G=a;this.C=b||a;this.J=this.C.document;this.V=void 0}ca.prototype.createElement=function(a,b,c){a=this.J.createElement(a);if(b)for(var d in b)if(b.hasOwnProperty(d))if("style"==d){var e=a,f=b[d];da(this)?e.setAttribute("style",f):e.style.cssText=f}else a.setAttribute(d,b[d]);c&&a.appendChild(this.J.createTextNode(c));return a};function s(a,b,c){a=a.J.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(c,a.lastChild)}
function t(a,b){return a.createElement("link",{rel:"stylesheet",href:b})}function ea(a,b){return a.createElement("script",{src:b})}function u(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function v(a,b){for(var c=a.className.split(/\s+/),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}
function fa(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return h;return m}function da(a){if(void 0===a.V){var b=a.J.createElement("p");b.innerHTML='<a style="top:1px;">w</a>';a.V=/top/.test(b.getElementsByTagName("a")[0].getAttribute("style"))}return a.V}function w(a){var b=a.C.location.protocol;"about:"==b&&(b=a.G.location.protocol);return"https:"==b?"https:":"http:"};function x(a,b,c){this.H=a;this.ha=b;this.Ba=c};function y(a,b,c,d,e,f,g,j){this.L=a;this.Aa=b;this.ja=c;this.wa=d;this.ya=e;this.xa=f;this.va=g;this.k=j}y.prototype.getName=function(){return this.L};function z(a,b){this.a=a;this.q=b}var ga=new y("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",void 0,new x(m,m,m));
z.prototype.parse=function(){var a;if(-1!=this.a.indexOf("MSIE")){a=A(this);var b=B(this),c=C(this.a,/(MSIE [\d\w\.]+)/,1);if(""!=c){var d=c.split(" "),c=d[0],d=d[1],e=D(d),f=D(b);a=new y(c,d,c,d,a,b,E(this.q),new x("Windows"==a&&6<=e.e||"Windows Phone"==a&&8<=f.e,m,m))}else a=new y("MSIE","Unknown","MSIE","Unknown",a,b,E(this.q),new x(m,m,m))}else if(-1!=this.a.indexOf("Opera"))a=ha(this);else if(/AppleWeb(K|k)it/.test(this.a)){a=A(this);var b=B(this),c=C(this.a,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,
1),g=m;""==c&&(c="Unknown");d=D(c);g=D(b);e="Unknown";-1!=this.a.indexOf("Chrome")||-1!=this.a.indexOf("CrMo")||-1!=this.a.indexOf("CriOS")?e="Chrome":/Silk\/\d/.test(this.a)?e="Silk":"BlackBerry"==a||"Android"==a?e="BuiltinBrowser":-1!=this.a.indexOf("Safari")?e="Safari":-1!=this.a.indexOf("AdobeAIR")&&(e="AdobeAIR");f="Unknown";"BuiltinBrowser"==e?f="Unknown":/Silk\/\d/.test(this.a)?f=C(this.a,/Silk\/([\d\._]+)/,1):-1!=this.a.indexOf("Version/")?f=C(this.a,/Version\/([\d\.\w]+)/,1):"Chrome"==e?
f=C(this.a,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):"AdobeAIR"==e&&(f=C(this.a,/AdobeAIR\/([\d\.]+)/,1));"AdobeAIR"==e?(g=D(f),g=2<g.e||2==g.e&&5<=g.u):g="BlackBerry"==a?10<=g.e:"Android"==a?2<g.e||2==g.e&&1<g.u:526<=d.e||525<=d.e&&13<=d.u;a=new y(e,f,"AppleWebKit",c,a,b,E(this.q),new x(g,536>d.e||536==d.e&&11>d.u,"iPhone"==a||"iPad"==a||"iPod"==a||"Macintosh"==a))}else-1!=this.a.indexOf("Gecko")?(b=a="Unknown",c=m,-1!=this.a.indexOf("Firefox")?(a="Firefox",d=C(this.a,/Firefox\/([\d\w\.]+)/,1),""!=d&&
(c=D(d),b=d,c=3<=c.e&&5<=c.u)):-1!=this.a.indexOf("Mozilla")&&(a="Mozilla"),d=C(this.a,/rv:([^\)]+)/,1),""==d?d="Unknown":c||(c=D(d),c=1<c.e||1==c.e&&9<c.u||1==c.e&&9==c.u&&2<=c.qa||d.match(/1\.9\.1b[123]/)!=l||d.match(/1\.9\.1\.[\d\.]+/)!=l),a=new y(a,b,"Gecko",d,A(this),B(this),E(this.q),new x(c,m,m))):a=ga;return a};
function A(a){var b=C(a.a,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=C(a.a,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function B(a){var b=C(a.a,/(OS X|Windows NT|Android|CrOS) ([^;)]+)/,2);return b||(b=C(a.a,/Windows Phone( OS)? ([^;)]+)/,2))||(b=C(a.a,/(iPhone )?OS ([\d_]+)/,2))||(b=C(a.a,/Linux ([i\d]+)/,1))?b:(a=C(a.a,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function ha(a){var b="Unknown",c="Unknown",d=C(a.a,/(Presto\/[\d\w\.]+)/,1);""!=d?(c=d.split("/"),b=c[0],c=c[1]):(-1!=a.a.indexOf("Gecko")&&(b="Gecko"),d=C(a.a,/rv:([^\)]+)/,1),""!=d&&(c=d));if(-1!=a.a.indexOf("Opera Mini/"))return d=C(a.a,/Opera Mini\/([\d\.]+)/,1),""==d&&(d="Unknown"),new y("OperaMini",d,b,c,A(a),B(a),E(a.q),new x(m,m,m));if(-1!=a.a.indexOf("Version/")){var e=C(a.a,/Version\/([\d\.]+)/,1);if(""!=e)return d=D(e),new y("Opera",e,b,c,A(a),B(a),E(a.q),new x(10<=d.e,m,m))}e=C(a.a,/Opera[\/ ]([\d\.]+)/,
1);return""!=e?(d=D(e),new y("Opera",e,b,c,A(a),B(a),E(a.q),new x(10<=d.e,m,m))):new y("Opera","Unknown",b,c,A(a),B(a),E(a.q),new x(m,m,m))}function D(a){a=/([0-9]+)(?:\.([0-9]+)(?:\.([0-9]+)?)?)?/.exec(a);var b={};a&&(b.e=parseInt(a[1]||-1,10),b.u=parseInt(a[2]||-1,10),b.qa=parseInt(a[3]||-1,10));return b}function C(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function E(a){if(a.documentMode)return a.documentMode};function ia(a){this.na=a||"-"}ia.prototype.f=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.na)};function F(a,b){this.L=a;this.W=4;this.M="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.M=c[1],this.W=parseInt(c[2],10))}F.prototype.getName=function(){return this.L};function G(a){return a.M+a.W}function ja(a){var b=4,c="n",d=l;a&&((d=a.match(/(normal|oblique|italic)/i))&&d[1]&&(c=d[1].substr(0,1).toLowerCase()),(d=a.match(/([1-9]00|normal|bold)/i))&&d[1]&&(/bold/i.test(d[1])?b=7:/[1-9]00/.test(d[1])&&(b=parseInt(d[1].substr(0,1),10))));return c+b};function ka(a,b,c){this.c=a;this.h=b;this.P=c;this.j="wf";this.g=new ia("-")}function la(a){u(a.h,a.g.f(a.j,"loading"));H(a,"loading")}function I(a){v(a.h,a.g.f(a.j,"loading"));fa(a.h,a.g.f(a.j,"active"))||u(a.h,a.g.f(a.j,"inactive"));H(a,"inactive")}function H(a,b,c){if(a.P[b])if(c)a.P[b](c.getName(),G(c));else a.P[b]()};function J(a,b){this.c=a;this.B=b;this.m=this.c.createElement("span",{},this.B)}
function K(a,b){var c=a.m,d;d=[];for(var e=b.L.split(/,\s*/),f=0;f<e.length;f++){var g=e[f].replace(/['"]/g,"");-1==g.indexOf(" ")?d.push(g):d.push("'"+g+"'")}d=d.join(",");e="normal";f=b.W+"00";"o"===b.M?e="oblique":"i"===b.M&&(e="italic");d="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+d+";"+("font-style:"+e+";font-weight:"+f+";");da(a.c)?c.setAttribute("style",d):c.style.cssText=
d}function L(a){s(a.c,"body",a.m)}J.prototype.remove=function(){var a=this.m;a.parentNode&&a.parentNode.removeChild(a)};function M(a,b,c,d,e,f,g,j){this.I=a;this.Z=b;this.c=c;this.o=d;this.B=j||"BESbswy";this.k=e;this.t={};this.N=f||5E3;this.ba=g||l;this.A=this.z=l;a=new J(this.c,this.B);L(a);for(var p in N)N.hasOwnProperty(p)&&(K(a,new F(N[p],G(this.o))),this.t[N[p]]=a.m.offsetWidth);a.remove()}var N={ua:"serif",ta:"sans-serif",sa:"monospace"};
M.prototype.start=function(){this.z=new J(this.c,this.B);L(this.z);this.A=new J(this.c,this.B);L(this.A);this.ea=r();K(this.z,new F(this.o.getName()+",serif",G(this.o)));K(this.A,new F(this.o.getName()+",sans-serif",G(this.o)));this.Q()};function ma(a,b,c){for(var d in N)if(N.hasOwnProperty(d)&&b===a.t[N[d]]&&c===a.t[N[d]])return h;return m}
M.prototype.Q=function(){var a=this.z.m.offsetWidth,b=this.A.m.offsetWidth;a===this.t.serif&&b===this.t["sans-serif"]||this.k.ha&&ma(this,a,b)?r()-this.ea>=this.N?this.k.ha&&ma(this,a,b)&&(this.ba===l||this.ba.hasOwnProperty(this.o.getName()))?O(this,this.I):O(this,this.Z):oa(this):O(this,this.I)};function oa(a){setTimeout(n(function(){this.Q()},a),25)}function O(a,b){a.z.remove();a.A.remove();b(a.o)};function P(a,b,c,d){this.c=b;this.w=c;this.R=0;this.fa=this.aa=m;this.N=d;this.k=a.k}P.prototype.watch=function(a,b,c,d){var e=a.length;if(0===e&&d)I(this.w);else{this.R+=e;d&&(this.aa=d);for(d=0;d<e;d++){var f=a[d],g=b[f.getName()],j=this.w,p=f;u(j.h,j.g.f(j.j,p.getName(),G(p).toString(),"loading"));H(j,"fontloading",p);j=n(this.ka,this);p=n(this.la,this);(new c(j,p,this.c,f,this.k,this.N,l,g)).start()}}};
P.prototype.ka=function(a){var b=this.w;v(b.h,b.g.f(b.j,a.getName(),G(a).toString(),"loading"));v(b.h,b.g.f(b.j,a.getName(),G(a).toString(),"inactive"));u(b.h,b.g.f(b.j,a.getName(),G(a).toString(),"active"));H(b,"fontactive",a);this.fa=h;pa(this)};P.prototype.la=function(a){var b=this.w;v(b.h,b.g.f(b.j,a.getName(),G(a).toString(),"loading"));fa(b.h,b.g.f(b.j,a.getName(),G(a).toString(),"active"))||u(b.h,b.g.f(b.j,a.getName(),G(a).toString(),"inactive"));H(b,"fontinactive",a);pa(this)};
function pa(a){0==--a.R&&a.aa&&(a.fa?(a=a.w,v(a.h,a.g.f(a.j,"loading")),v(a.h,a.g.f(a.j,"inactive")),u(a.h,a.g.f(a.j,"active")),H(a,"active")):I(a.w))};function Q(a,b,c){this.G=a;this.X=b;this.a=c;this.S=this.T=0}function R(a,b){S.X.ca[a]=b}Q.prototype.load=function(a){var b=a.context||this.G;this.c=new ca(this.G,b);b=new ka(this.c,b.document.documentElement,a);if(this.a.k.H){var c=this.X,d=this.c,e=[],f;for(f in a)if(a.hasOwnProperty(f)){var g=c.ca[f];g&&e.push(g(a[f],d))}a=a.timeout;this.S=this.T=e.length;a=new P(this.a,this.c,b,a);f=0;for(c=e.length;f<c;f++)d=e[f],d.D(this.a,n(this.ma,this,d,b,a))}else I(b)};
Q.prototype.ma=function(a,b,c,d){var e=a.Y?a.Y():M,f=this;d?a.load(function(a){var d=0==--f.T;d&&la(b);setTimeout(function(){c.watch(a,{},e,d)},0)}):(a=0==--this.T,this.S--,a&&(0==this.S?I(b):la(b)),c.watch([],{},e,a))};var qa=window,sa=(new z(navigator.userAgent,document)).parse(),S=qa.WebFont=new Q(window,new function(){this.ca={}},sa);S.load=S.load;function T(a,b,c){this.a=a;this.c=b;this.d=c;this.p=[]}
T.prototype.D=function(a,b){var c=this,d=c.d.projectId,e=c.d.version;if(d){var f=c.c.createElement("script");f.id="__MonotypeAPIScript__"+d;var g=this.c.C,j=m;f.onload=f.onreadystatechange=function(){if(!j&&(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState)){j=h;if(g["__mti_fntLst"+d]){var e=g["__mti_fntLst"+d]();if(e)for(var k=0;k<e.length;k++)c.p.push(new F(e[k].fontfamily))}b(a.k.H);f.onload=f.onreadystatechange=l}};f.src=c.F(d,e);s(this.c,"head",f)}else b(h)};
T.prototype.F=function(a,b){var c=w(this.c),d=(this.d.api||"fast.fonts.com/jsapi").replace(/^.*http(s?):(\/\/)?/,"");return c+"//"+d+"/"+a+".js"+(b?"?v="+b:"")};T.prototype.load=function(a){a(this.p)};R("monotype",function(a,b){var c=(new z(navigator.userAgent,document)).parse();return new T(c,b,a)});function U(a,b){this.c=a;this.d=b}var ta={regular:"n4",bold:"n7",italic:"i4",bolditalic:"i7",r:"n4",b:"n7",i:"i4",bi:"i7"};U.prototype.D=function(a,b){return b(a.k.H)};U.prototype.load=function(a){s(this.c,"head",t(this.c,w(this.c)+"//webfonts.fontslive.com/css/"+this.d.key+".css"));for(var b=this.d.families,c=[],d=0,e=b.length;d<e;d++)c.push.apply(c,ua(b[d]));a(c)};
function ua(a){var b=a.split(":");a=b[0];if(b[1]){for(var c=b[1].split(","),b=[],d=0,e=c.length;d<e;d++){var f=c[d];if(f){var g=ta[f];b.push(g?g:f)}}c=[];for(d=0;d<b.length;d+=1)c.push(new F(a,b[d]));return c}return[new F(a)]}R("ascender",function(a,b){return new U(b,a)});function W(a,b){this.c=a;this.d=b;this.p=[]}W.prototype.F=function(a){return w(this.c)+(this.d.api||"//f.fontdeck.com/s/css/js/")+(this.c.C.location.hostname||this.c.G.location.hostname)+"/"+a+".js"};
W.prototype.D=function(a,b){var c=this.d.id,d=this.c.C,e=this;c?(d.__webfontfontdeckmodule__||(d.__webfontfontdeckmodule__={}),d.__webfontfontdeckmodule__[c]=function(a,c){for(var d=0,p=c.fonts.length;d<p;++d){var k=c.fonts[d];e.p.push(new F(k.name,ja("font-weight:"+k.weight+";font-style:"+k.style)))}b(a)},c=ea(this.c,this.F(c)),s(this.c,"head",c)):b(h)};W.prototype.load=function(a){a(this.p)};R("fontdeck",function(a,b){return new W(b,a)});function X(a,b,c,d,e,f,g,j){M.call(this,a,b,c,d,e,f,g,j);a=["Times New Roman","Arial","Times","Sans","Serif"];b=G(this.o);c=a.length;d={};e=new J(this.c,this.B);L(e);K(e,new F(a[0],b));d[e.m.offsetWidth]=h;for(f=1;f<c;f++)g=a[f],K(e,new F(g,b)),d[e.m.offsetWidth]=h,"4"!=b.toString().charAt(1)&&(K(e,new F(g,b.charAt(0)+"4")),d[e.m.offsetWidth]=h);e.remove();this.v=d;this.ia=m;this.oa=this.t.serif;this.pa=this.t["sans-serif"]}function va(){}va.prototype=M.prototype;X.za=M.prototype;X.prototype=new va;
var wa={Arimo:h,Cousine:h,Tinos:h};X.prototype.Q=function(){var a=this.z.m.offsetWidth,b=this.A.m.offsetWidth;!this.ia&&(a==b&&this.v[a])&&(this.v={},this.ia=this.v[a]=h);(this.oa!=a||this.pa!=b)&&!this.v[a]&&!this.v[b]?O(this,this.I):r()-this.ea>=this.N?this.v[a]&&this.v[b]&&wa[this.o.getName()]?O(this,this.I):O(this,this.Z):oa(this)};function xa(a,b,c){this.O=a?a:b+ya;this.s=[];this.U=[];this.ga=c||""}var ya="//fonts.googleapis.com/css";xa.prototype.f=function(){if(0==this.s.length)throw Error("No fonts to load !");if(-1!=this.O.indexOf("kit="))return this.O;for(var a=this.s.length,b=[],c=0;c<a;c++)b.push(this.s[c].replace(/ /g,"+"));a=this.O+"?family="+b.join("%7C");0<this.U.length&&(a+="&subset="+this.U.join(","));0<this.ga.length&&(a+="&text="+encodeURIComponent(this.ga));return a};function za(a){this.s=a;this.da=[];this.K={}}
var Aa={latin:"BESbswy",cyrillic:"&#1081;&#1103;&#1046;",greek:"&#945;&#946;&#931;",khmer:"&#x1780;&#x1781;&#x1782;",Hanuman:"&#x1780;&#x1781;&#x1782;"},Ba={thin:"1",extralight:"2","extra-light":"2",ultralight:"2","ultra-light":"2",light:"3",regular:"4",book:"4",medium:"5","semi-bold":"6",semibold:"6","demi-bold":"6",demibold:"6",bold:"7","extra-bold":"8",extrabold:"8","ultra-bold":"8",ultrabold:"8",black:"9",heavy:"9",l:"3",r:"4",b:"7"},Ca={i:"i",italic:"i",n:"n",normal:"n"},Da=RegExp("^(thin|(?:(?:extra|ultra)-?)?light|regular|book|medium|(?:(?:semi|demi|extra|ultra)-?)?bold|black|heavy|l|r|b|[1-9]00)?(n|i|normal|italic)?$");
za.prototype.parse=function(){for(var a=this.s.length,b=0;b<a;b++){var c=this.s[b].split(":"),d=c[0].replace(/\+/g," "),e=["n4"];if(2<=c.length){var f;var g=c[1];f=[];if(g)for(var g=g.split(","),j=g.length,p=0;p<j;p++){var k;k=g[p];if(k.match(/^[\w]+$/)){k=Da.exec(k.toLowerCase());var q=void 0;if(k==l)q="";else{q=void 0;q=k[1];if(q==l||""==q)q="4";else var na=Ba[q],q=na?na:isNaN(q)?"4":q.substr(0,1);q=[k[2]==l||""==k[2]?"n":Ca[k[2]],q].join("")}k=q}else k="";k&&f.push(k)}0<f.length&&(e=f);3==c.length&&
(c=c[2],f=[],c=!c?f:c.split(","),0<c.length&&(c=Aa[c[0]])&&(this.K[d]=c))}this.K[d]||(c=Aa[d])&&(this.K[d]=c);for(c=0;c<e.length;c+=1)this.da.push(new F(d,e[c]))}};function Y(a,b,c){this.a=a;this.c=b;this.d=c}Y.prototype.D=function(a,b){b(a.k.H)};Y.prototype.Y=function(){return"AppleWebKit"==this.a.ja?X:M};Y.prototype.load=function(a){if("MSIE"==this.a.getName()&&this.d.blocking!=h){var b=n(this.$,this,a),c=function(){document.body?b():setTimeout(c,0)};c()}else this.$(a)};
Y.prototype.$=function(a){for(var b=this.c,c=new xa(this.d.api,w(b),this.d.text),d=this.d.families,e=d.length,f=0;f<e;f++){var g=d[f].split(":");3==g.length&&c.U.push(g.pop());var j="";2==g.length&&""!=g[1]&&(j=":");c.s.push(g.join(j))}d=new za(d);d.parse();s(b,"head",t(b,c.f()));a(d.da,d.K)};R("google",function(a,b){var c=(new z(navigator.userAgent,document)).parse();return new Y(c,b,a)});function Z(a,b){this.c=a;this.d=b;this.p=[]}Z.prototype.F=function(a){var b=w(this.c);return(this.d.api||b+"//use.typekit.net")+"/"+a+".js"};
Z.prototype.D=function(a,b){var c=this.d.id,d=this.d,e=this.c.C,f=this;c?(e.__webfonttypekitmodule__||(e.__webfonttypekitmodule__={}),e.__webfonttypekitmodule__[c]=function(c){c(a,d,function(a,c,d){for(var e=0;e<c.length;e+=1){var g=d[c[e]];if(g)for(var V=0;V<g.length;V+=1)f.p.push(new F(c[e],g[V]));else f.p.push(new F(c[e]))}b(a)})},c=ea(this.c,this.F(c)),s(this.c,"head",c)):b(h)};Z.prototype.load=function(a){a(this.p)};R("typekit",function(a,b){return new Z(b,a)});function $(a,b){this.c=a;this.d=b}$.prototype.load=function(a){var b,c,d=this.d.urls||[],e=this.d.families||[];b=0;for(c=d.length;b<c;b++)s(this.c,"head",t(this.c,d[b]));d=[];b=0;for(c=e.length;b<c;b++){var f=e[b].split(":");if(f[1])for(var g=f[1].split(","),j=0;j<g.length;j+=1)d.push(new F(f[0],g[j]));else d.push(new F(f[0]))}a(d)};$.prototype.D=function(a,b){return b(a.k.H)};R("custom",function(a,b){return new $(b,a)});window.WebFontConfig&&S.load(window.WebFontConfig);
})(this,document);
