#!/bin/bash

APP='ajaxgoogleapis'
# Retrieve arguments
public_site=$1
domain='ajax.googleapis.com'
path='/ajax/libs'

sudo yunohost app setting $APP public_site -v $public_site

#Create ajax.googleapis.com domain
if [[ -n $(sudo yunohost domain list | grep $domain) ]]; then
    echo 'the domain is already installed'
else
    #sudo yunohost domain add '$domain'
    echo 'you need to setup $domain before'
fi

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $APP
if [[ ! $? -eq 0 ]]; then
    exit 1
fi


# Copy files to the right place
final_path=/var/www/$APP
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

# Set permissions to roundcube directory
sudo chown -R www-data: $final_path


# Configure Nginx
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$APP.conf

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
if [ "$public_site" = "Yes" ];
then
	sudo yunohost app setting $APP skipped_uris -v "/"
fi
sudo yunohost app ssowatconf
